swagger: "2.0"
info:
  description: "This is a sample API Server."
  version: "1.0.0"
  title: "Boot-Swag"
  termsOfService: "http://guesser.io/terms/"
  contact:
    email: "apiteam@pivotal.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8081"
basePath: "/api"
tags:
  - name: "bootswag"
    description: "All good guesses count"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
schemes:
  - "http"
paths:
  /donut:
    get:
      tags:
        - "desert-controller"
      summary: "Available Donuts"
      description: "All generated donuts returned."
      operationId: "myDonuts"
      consumes:
        - "*/*"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Donut"
        400:
          description: "Invalid status value"
    post:
      tags:
        - "desert-controller"
      summary: "Add a new donut"
      description: ""
      operationId: "addDonut"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Donut object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Donut"
      responses:
        405:
          description: "Invalid input"
  /maincourse:
    get:
      tags:
        - "maincourse-controller"
      summary: "Available maincourse"
      description: "All generated maincourse returned."
      operationId: "myMaincourse"
      consumes:
        - "*/*"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Maincourse"
        400:
          description: "Invalid status value"
definitions:
  Donut:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      size:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Donut"
  Maincourse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      size:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Maincourse"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"